name = "img-proxy"
main = "worker.js"
compatibility_date = "2025-03-03"
minify = true

kv_namespaces = [
  { binding = "IMG_PROXY_CACHE", id = "216d1c12b8964465a7c37ce050c54d54" }
]

[triggers]
crons = ["30 0,4,9,13,18,22 * * *"]

[observability]
enabled = true
head_sampling_rate = 1.00