name = "img-proxy"
main = "build/index.js"
compatibility_date = "2026-09-01"

[build]
command = "cargo install -q worker-build && worker-build --release --panic-unwind"

[[kv_namespaces]]
binding = "IMAGES"
id = "19b92535d5274086a71b4892d2137599"